### ISSUE TITLE
Enable POWER Support for application

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/application#110]
The dockerfile https://github.com/kubernetes-sigs/application/blob/master/Dockerfile only support x86 now, it is better to enable POWER support as well.

**Comment by barney-s** [comment]
Thanks for the PR. Do you know how to enable that support ?

**Comment by gyliu513** [comment]
@barney-s  We can use cross compile in Go to build POWER docker images, but the problem is we cannot test the docker image.
