### ISSUE TITLE
What is the use of ConfigMapKeySelector? How to get ConfigMap in app get?

### ISSUE THREAD

**Issue by hemantha-kumara** [kubernetes-sigs/application#112]
Can you explain what is the use of ConfigMapKeySelector. Is it used by the Application to list the configmaps that are used by it?

When an application is created and "ConfigMap" is included in the application definition, the output of 

> kubectl get application 

does not list the configMap. I have looked into the issue [ConfigMap not listed](https://github.com/kubernetes-sigs/application/issues/104) where the user had an incorrect Group. The Group is correctly set to core in my case.

Are these two related?
@nrchakradhar

**Comment by barney-s** [comment]
Try using 

```
group: v1
kind: ConfigMap
```

**Comment by janetkuo** [comment]
Ref #113

Please try again using `v1` (instead of `core`) as group. If it still doesn't work, please reopen this issue. 

cc @nan-yu for doc improvement

**Comment by nan-yu** [comment]
sample updated in PR https://github.com/kubernetes-sigs/application/pull/156
