### ISSUE TITLE
 Improve userAgent for Application Controller Manager

### ISSUE THREAD

**Issue by barney-s** [kubernetes-sigs/application#125]
The userAgent shows up as  “manager/v0.0.0”, which really doesn’t help identify what controller it is. This is useful when debugging the source of changes in the API server audit logs.

**Comment by barney-s** [comment]
With the upcoming move to kubebuilder 2 this should be resolved.
@nan-yu

**Comment by janetkuo** [comment]
> With the upcoming move to kubebuilder 2 this should be resolved.

ref #139

**Comment by barney-s** [comment]
kubebuilder v2 changes merged. Closing this.
