### ISSUE TITLE
[Question] CRD in componentKinds?

### ISSUE THREAD

**Issue by tzununbekov** [kubernetes-sigs/application#136]
Repository [readme](https://github.com/kubernetes-sigs/application/blob/88337a130765b8dd8498a209ea0859fc048dde06/README.md#application-objects) says that Application object can aggregate different kinds of components including CRD, but I couldn't make it work with any kind of custom resources. My humble attempt to debug controller code showed that there is no CRD resources in schema known types here:
https://github.com/kubernetes-sigs/application/blob/13e611d2b996a79c56f239d63c2679857d681aad/pkg/apis/app/v1beta1/application.go#L76-L86
Can anyone share an example Application object with CRD as component kind? Extra thanks if it would be Knative [serving](https://github.com/knative/serving) kind

**Comment by janetkuo** [comment]
@barney-s @nan-yu

**Comment by barney-s** [comment]
It should be supported. We will investigate and fix it.

**Comment by tzununbekov** [comment]
@barney-s any updates? could you at least confirm that this issue exist?

**Comment by barney-s** [comment]
@tzununbekov - We were in the midst of rearchitecting the controller. Its done now. 
Would you retest with the latest controller. Please attach the spec you used.

**Comment by barney-s** [comment]
@tzununbekov - With the latest changes the we use restMapper to get the GVK for the given GK
https://github.com/kubernetes-sigs/application/blob/master/controllers/application_controller.go#L117

Could you check if this works for the Knative types.

We will add e2e test cases to cover these scenarios.

**Comment by tzununbekov** [comment]
@barney-s thanks for the update, but I'm having issues with CRD deployment. Go build fails with a following error:
```
# k8s.io/client-go/rest
../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```
looks like dependencies issue :thinking: 

I wanted to go with `make deploy` approach as readme suggests, but I don't like that it tries to install different tools which I already have installed (not in /bin/* as Makefile expects, but in go binaries)

Last time when I deployed Application CRD I had several local fixes in installation scripts and configs which I reset to pull latest commits. If anyone else could test described case with any CRD component kinds that would be great!

**Comment by barney-s** [comment]
Regarding the build that seems odd. We do not check for compiler version may be we need to ?
We are setting the client-go version in go.mod to.  k8s.io/client-go v0.17.0

Are you sure the deps are being installed as part of "make tidy" and "make all" ?

The reason we install in hack/bin/* is to use a specific version of the tooling binaries.
We did not want to override the binaries that are under gopath/bin.

We have an open pull request for an example that uses a CRD. Please comment on that if it is different from what you are testing. We will update that and make sure that case works.

https://github.com/kubernetes-sigs/application/pull/158/files#diff-41e54dafabe5af64bad57136dde2a1adR108

**Comment by tzununbekov** [comment]
@barney-s you're right, dependency problem was on my side. And yes, new example with CRD looks like something that I tried to achieve. Thanks for helping with this issue!

**Comment by barney-s** [comment]
@tzununbekov  - I believe this is fixed now. 
Would you please confirm.

/close
