### ISSUE TITLE
Application privacy policy

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/application#14]
There is a discuss on Helm charts on how applications can collect analytics on not. It dawned on me that may be there should be a field for setting link to a privacy policy document in the application CRD. Is the `Links ` field enough for that?

ref: https://github.com/kubernetes/charts/issues/4697#issuecomment-378746444

cc: @mattfarina

**Comment by konryd** [comment]
Links and Notes both should be able to accomodate this. 

This looks like an example of well-known "type" of a link - something that was discussed in #4 ([link to conversation](https://github.com/kubernetes-sigs/application/pull/4#discussion_r176302278)).
