### ISSUE TITLE
Condition Ready is True when Deployment replicas are 0

### ISSUE THREAD

**Issue by lewismarshall** [kubernetes-sigs/application#148]
Using - master@01d8bf78

It would seem as though the controller isn't updating the status when deployment scaled (or even if a deployment deleted and re-created with bad image):
```
$ kubectl -n captain-system scale deploy/captain-controller-manager --replicas=0
deployment.extensions/captain-controller-manager scaled
$ date ;kubectl -n captain-system get deploy,svc -l app=captain -o wide
Fri  7 Feb 2020 12:34:34 GMT
NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES                                 SELECTOR
deployment.extensions/captain-controller-manager   0/0     0            0           5d1h   manager      index.alauda.cn/claas/captain:v0.9.4   app=captain

NAME                      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)            AGE    SELECTOR
service/captain-webhook   ClusterIP   10.0.0.181   <none>        443/TCP,6060/TCP   5d1h   app=captain
```
And then the pertinent logs after the next reconciliation period:
```
$kubectl -n application-system logs -l control-plane=application-manager -c manager
...
2020-02-07T12:36:31.857Z	INFO	controllers.Application	NoMappingForGK	{"application": "captain-system/captain", "gk": "Service.controller"}
2020-02-07T12:36:33.910Z	INFO	controllers.Application	NoMappingForGK	{"application": "captain-system/captain", "gk": "Deployment.controller"}
2020-02-07T12:36:33.910Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "application", "request": "captain-system/captain"}
...
```
And finally the application object after the reconciliation:
```
$ date ; kubectl -n captain-system get application -o yaml
Fri  7 Feb 2020 12:37:37 GMT
apiVersion: v1
items:
- apiVersion: app.k8s.io/v1beta1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"app.k8s.io/v1beta1","kind":"Application","metadata":{"annotations":{},"labels":{"kore-direct":"true"},"name":"captain","namespace":"captain-system"},"spec":{"assemblyPhase":"Pending","componentKinds":[{"group":"controller","kind":"Service"},{"group":"controller","kind":"Deployment"}],"descriptor":{"description":"A controller for deploying helm3 charts","type":"captain","version":""},"selector":{"matchLabels":{"app":"captain","service_name":"captain"}}}}
    creationTimestamp: "2020-02-07T11:23:21Z"
    generation: 2
    labels:
      kore-direct: "true"
    name: captain
    namespace: captain-system
    resourceVersion: "8742901"
    selfLink: /apis/app.k8s.io/v1beta1/namespaces/captain-system/applications/captain
    uid: 3fa08887-499c-11ea-8449-42010a9a009c
  spec:
    assemblyPhase: Pending
    componentKinds:
    - group: controller
      kind: Service
    - group: controller
      kind: Deployment
    descriptor:
      description: A controller for deploying helm3 charts
      type: captain
      version: ""
    selector:
      matchLabels:
        app: captain
  status:
    conditions:
    - lastTransitionTime: "2020-02-07T11:23:24Z"
      lastUpdateTime: "2020-02-07T11:23:24Z"
      message: all components ready
      reason: ComponentsReady
      status: "True"
      type: Ready
    - lastTransitionTime: "2020-02-07T11:23:24Z"
      lastUpdateTime: "2020-02-07T11:23:24Z"
      message: No error seen
      reason: NoError
      status: "False"
      type: Error
    observedGeneration: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by barney-s** [comment]
@lewismarshall Thanks for the issue. 
We will more tests around this case.

@nan-yu FYI

**Comment by nan-yu** [comment]
@lewismarshall 
I ran some tests on my end and thought the controller is doing the right thing. Basically, the controller computes the deployment status based on `conditions`. It considers the deployment status as `Ready` in the following scenarios:
- if no conditions are found in deloyment status, OR
- if condition.type == `Processing` is found, condition.status must be true and condition.reason must be `NewReplicaSetAvailable` AND
- if condition.type == `Available` is found, condition.status must be true

# Scaling down deployment replicas to 0
When deployment replicas is set to zero, the deployment is considered to be Ready as Deployment has minimum availability, i.e. 0.
Hence, in this case, there's no need to update the application status.

# Update deployment with a bad image
Can you re-test this scenario? I updated the deployment with a bad image. The condition status for `Available` type is "false" with a `MinimumReplicasUnavailable` reason.
```
status:
  conditions:
  - lastTransitionTime: "2020-02-07T18:24:23Z"
    lastUpdateTime: "2020-02-07T18:27:18Z"
    message: ReplicaSet "nanyu-hello-6c4f6d79bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-07T18:46:38Z"
    lastUpdateTime: "2020-02-07T18:46:38Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 6
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

The controller did update the application status with the following:
```
status:
  components:
  - group: apps
    kind: Deployment
    link: /apis/apps/v1/namespaces/default/deployments/nanyu-hello
    name: nanyu-hello
    status: InProgress
  - group: batch
    kind: Job
    link: /apis/batch/v1/namespaces/default/jobs/pi
    name: pi
    status: Ready
  - kind: Service
    link: /api/v1/namespaces/default/services/wordpress-webserver-svc
    name: wordpress-webserver-svc
    status: Ready
  conditions:
  - lastTransitionTime: "2020-02-07T18:46:39Z"
    lastUpdateTime: "2020-02-07T18:46:39Z"
    message: some components not ready
    reason: ComponentsNotReady
    status: "False"
    type: Ready
  - lastTransitionTime: "2020-02-07T18:24:23Z"
    lastUpdateTime: "2020-02-07T18:24:23Z"
    message: No error seen
    reason: NoError
    status: "False"
    type: Error
  observedGeneration: 1
                             
```

**Comment by lewismarshall** [comment]
@nan-yu  fair enough regarding scaled down:
> Hence, in this case, there's no need to update the application status.

Not sure about this one though:
> * if no conditions are found in deloyment status

If the objects can't be found due to:
- application not yet deployed
- bad select labels (my bad)
- bad RBAC for operator (investigation)

Maybe this shouldn't be `Ready` but `Unknown`? Would like to use application kind to work out when applications are really `Ready` but at the moment it's kind of "not really known so  let's assume `Ready`"?

Not sure if that's fair as I may be missing something. An illustration for this is below (bad RBAC):
```
status:
  conditions:
  - lastTransitionTime: "2020-02-13T16:30:39Z"
    lastUpdateTime: "2020-02-13T16:30:39Z"
    message: all components ready
    reason: ComponentsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-02-13T16:30:39Z"
    lastUpdateTime: "2020-02-13T16:30:39Z"
    message: 'deployments.apps is forbidden: User "system:serviceaccount:application-system:default"
      cannot list resource "deployments" in API group "apps" in the namespace "kore-system"'
    reason: ErrorSeen
    status: "True"
    type: Error
```

**Comment by nan-yu** [comment]
I agree it's unfair to set an application `Ready` when it's actually `Unknown`. We updated how we compute resource status [here](https://github.com/kubernetes-sigs/application/pull/167/commits/cbeea89e2a6be136491bbbe2d65f7227279f33bc) based on this [public doc](https://docs.google.com/document/d/1RAPC5-LCb_VBpzvbpCLn8Z-7eilRAWmO0RGbVuChhPc/edit#heading=h.rqs3jxocuzbw).

For the bad RBAC error, the rules of the role has been [fixed](https://github.com/kubernetes-sigs/application/pull/155). You shouldn't see the error with the latest code.
To better handle cases like this, we set the application's condition to NotReady when error occurs in status-aggregation stage: [fix](https://github.com/kubernetes-sigs/application/pull/167/commits/c0e1c73fc52f09832d0963220bdba377a726bdcb).

@lewismarshall ^^

**Comment by barney-s** [comment]
@lewismarshall  - With the recent merges would this issue be closed ?

**Comment by lewismarshall** [comment]
@barney-s I think so, I will test now.

**Comment by lewismarshall** [comment]
> @barney-s I think so, I will test now.

@barney-s tried to re-build to test, unfortunately got this:

```
Get https://proxy.golang.org/cloud.google.com/go/@v/v0.38.0.zip: unexpected EOF
```
I'll try and test on Monday

**Comment by lewismarshall** [comment]
@barney-s yes I can confirm for the bad image the `Ready` condition is now `False` will now correctly show

**Comment by barney-s** [comment]
thanks for confirming @lewismarshall 
/close
