### ISSUE TITLE
Integrate ApplicationCRD with existing Kubernetes Distributions

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#165]
To make it easier for the user to get started with the ApplicationCRD the installation should close to other native API. 
Actions are to be identified and integration points could from multiple points:
- [ ] [kubernetes cluster addons](https://github.com/kubernetes-sigs/cluster-addons)
- [ ] Helm Chart
- [ ] Kubespray / Kubeadm / Kops options at installation or upgrade of a cluster
- [ ] Minikube options ?

I'll update the issue to keep track of progress. Please add other places it could be integrated

**Comment by cmoulliard** [comment]
@ant31 Is the `Kubernetes Cluster Addons` already [implemented](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/addons/0035-20190128-addons-via-operators.md) and available  with kubernetes ?
