### ISSUE TITLE
Release images and resources

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#166]
In order to use the ApplicationController/CRD the users should not have to clone and build themself images and resources. 

To get started a user would only have to do: 

```sh
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/application/$latest/deploy/recommended.yaml
```

Also required for #165

**Comment by barney-s** [comment]
How do you propose we make the release ? 
What are the artifacts ?

**Comment by ant31** [comment]
> How do you propose we make the release ?

- Publish a container with new tags. 
- Generate a all-in-one kubernetes-resource ready to be directly use with kubectl

 Both could be easily generated via the CI.
