### ISSUE TITLE
condition with a contradiction:  "type: Error, reason: "NoError"

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#170]
The following condition is confusing, it's in 'error', but reason is set to 'NoError'  

```
    - lastTransitionTime: "2020-02-18T12:22:01Z"
      lastUpdateTime: "2020-02-18T12:22:01Z"
      message: No error seen
      reason: NoError
      status: "False"
      type: Error
```

Is it expected, if yes: could we improve the message/reason fields ?

**Comment by ant31** [comment]
@nan-yu   is that intended ?

**Comment by nan-yu** [comment]
Yes, that's intended. The type `Error` with `False` status implies no error, which is in line with reason `NoError`.
Initially, I was thinking remove this condition. However, I saw somewhere documented that the guidelines around condition is to set the condition to false, not clear it. The absence implies **Unknown**, not **false**.
@ant31
