### ISSUE TITLE
Rename 'manager' to a more specific name: `kube-app-manager`

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#173]
As application aim to be more integrated and collocated with other 'managers' and controllers (#165) , logfiles, logs, binaries, labels, filename, rolebinding, roles... should be more specific to be facilitate identification, ownership and tooling (e.g grep on logs). 

I propose to rename `manager` to `kube-app-manager`

Please do a +1 before I go through this renaming.

cc @nan-yu @barney-s

**Comment by nan-yu** [comment]
Sounds good to me 
+1

**Comment by barney-s** [comment]
+1 thanks
