### ISSUE TITLE
Why is there a Webhook configuration ?

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#175]
I see several configuration files about enabling webhook, but is there any usage of webhook in the controller? What does this feature enables?

**Comment by nan-yu** [comment]
The webhook configuration is auto-generated by kubebuilder. We are not using it in the controller. Keeping it for now in case there is a need to enable it in the future. @ant31

**Comment by ant31** [comment]
@nan-yu ok, this what I guessed.
I've moved all related variables to webhook from the main configuration file (`default/kustomization.yaml`) to a separate one in #179, it's a little easier to see what 'useful' value you can tweak.

Thank you.
