### ISSUE TITLE
Add application go mod package 

### ISSUE THREAD

**Issue by barney-s** [kubernetes-sigs/application#181]
Consider creating a package that clients could use to:
1. List child objects given application object/NN
2. Compute the status (useful in cases where application controller is not installed, just CRD)

```golang
appmgr := application.NewApplicationManager(client)

// return an object that supports methods 
app := appmgr.GetAppCR(name, namespace)

// return list of unstructured
children := app.GetChildren()
```

Alternatively work with Rest client returned object
```golang
// return unstructured
appobj := restclient.Get(nn)

// get children ([]unstructured) given unstructured
children := application.GetChildren(appobj)
```

**Comment by ant31** [comment]
is there clients identified already?
