### ISSUE TITLE
is it desired to mark Ready even if errors happened?

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes-sigs/application#183]
introduced in:
https://github.com/kubernetes-sigs/application/pull/180

At the following line, it seems the controller will ONLY mark the application to be "ComponentsReady" when counts ready == expected AND there is some error? Is it desired?  
https://github.com/kubernetes-sigs/application/blob/master/controllers/application_controller.go#L99

**Comment by nan-yu** [comment]
@yuxiangqian Thanks for catching this! The whole point of #180 is to **NOT** mark aggregated condition ready when errors happen. It is a dummy typo.
We will consider adding more test cases with mock errors.
