### ISSUE TITLE
Application GUI Yet?

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/application#188]
I read the point of this project is for some 'visualization' of an app and its resources. Are there any examples at all of this CRD being 'visualized' anywhere? Are there plans for this to be a first class citizen of the [K8s Dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/)? 

I've been searching for something to display my Application CRD and have not come across anything yet.

**Comment by barney-s** [comment]
Thats a great point. It should be implemented as part of the dashboard project. We are working to standardize this CRD

**Comment by migueloller** [comment]
@kferrone, GCP will display applications in their dashboard and has first-class support for them.

**Comment by ant31** [comment]
@barney-s  is there any discussion / thread about adding it to the dashboard project ?

**Comment by barney-s** [comment]
Looks like there is an issue in the dashboard project: 
https://github.com/kubernetes/dashboard/issues/2891
 
Please chime in there. We can support from here.

**Comment by mattfarina** [comment]
@kferrone Visualization would be great. The Kubernetes dashboard is one place but other UIs can do that as well. GCP is one example of that but other 3rd party tools could, too.

**Comment by ant31** [comment]
K8s dashboard seems not ready to add CRD extensions neither natively nor via plugins: https://github.com/kubernetes/dashboard/issues/1599
Additional user-requests may change this ^. 

There's [kappnav.io](https://kappnav.io/) that provides a UI to manage applications on top of openshift or a standalone one on any kubernetes clusters. 
Also Google Cloud has an UI for applications

**Comment by nsainaney** [comment]
Hey all,
We [codezero.io](http://codezero.io) have been working on an application GUI that in alpha right now. It deals with Auth, Installing Apps & Launching apps, Resource management (compute, storage etc.), and App settings. Looking for feedback and just discovered this SIG. Definitely open to working together or collaborating. 

https://www.youtube.com/watch?v=fltBTy_bRZM&t=2s

<img width="1446" alt="Screen Shot 2020-10-05 at 9 19 47 AM" src="https://user-images.githubusercontent.com/306293/95105637-48e5cb80-06ec-11eb-86a6-b0cb0e32ebbc.png">
<img width="1446" alt="Screen Shot 2020-10-05 at 9 20 27 AM" src="https://user-images.githubusercontent.com/306293/95105643-4d11e900-06ec-11eb-8b0a-8e0e61081fce.png">
