### ISSUE TITLE
Make deploy fails due to missing docker image

### ISSUE THREAD

**Issue by gwkunze** [kubernetes-sigs/application#192]
Deploying v0.8.2 with `make deploy` successfully applies all the resources but the image referenced (`quay.io/kubernetes-sigs/kube-app-manager:v0.8.1` version probably needs to be updated as well) does not exist: https://quay.io/repository/kubernetes-sigs/kube-app-manager?tab=tags

**Comment by barney-s** [comment]
@ant31 - Would you please push the new images to quay.io repo. We just tagged the release.

**Comment by ant31** [comment]
The image have been pushed.
