### ISSUE TITLE
Generate clientset

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/application#200]
We would like to write a controller for Application crd using the approach shown in https://github.com/kubernetes/sample-controller project. Can you please generate clientset for application crds ?

**Comment by tamalsaha** [comment]
I have managed to do this in my fork https://github.com/kubepack/application/pull/1

But this requires moving the api/v1beta1 -> api/app/v1beta1 . I can open a pr if this change look acceptable.

**Comment by mattfarina** [comment]
@tamalsaha Did you know this project already has a controller? What are you trying to do with your controller?

**Comment by tamalsaha** [comment]
I want to programmatically create "Application" objects. So, generated clientset will be nice.
