### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/application#218]
Seems there is not much momentum anymore. Will there be regular maintenance from here on? Is this project deprecated? Are there alternatives out there?

**Comment by hairmare** [comment]
I make extensive use of [Argo CD](https://argoproj.github.io/argo-cd/) and only just noticed this repo. I am wondering if the ground work done here might help standardize what the various `kind: Application`  resouces have across various `apiVerson` specific definitions.

**Comment by red8888** [comment]
I get the impression that this effort is being driven by Google exclusively: https://cloud.google.com/kubernetes-applications

Are they just not trying super hard to court the wider open source community or does no one else give a crap about it?

There is actually a dashboard item in the GKE console for "Kubernetes Applications". I think this is just a GCP specific feature mostly for 3rd parties to support easy install of their apps onto GKE clusters.

**Comment by janetkuo** [comment]
Yes, Google has historically driven the Application CRD work. Google's general focus is to support complementary technologies that can be composed with existing solutions in the ecosystem. The primary focus of the App CRD is Status / and metadata (which Google exposes in the GKE UI), in case our customers would like a deeper integration with the GKE UI for their app teams.

@kow3ns might have some thoughts as well given that he's the original author of it.

**Comment by red8888** [comment]
Should open any issues/questions I have with GCP support instead of here? I get the impression these github issues aren't going to be front and center for them.
