### ISSUE TITLE
Dear Google, how do I contribute to this project? Are you abandoning the Application CRD?

### ISSUE THREAD

**Issue by borgilb** [kubernetes-sigs/application#223]
I being dramatic to try to get some response here :)

I really like the Application CRD and want to keep using it. I know Google is the only one driving its development. Its officially supported by the GKE UI and from what I have heard possible future GKE features might use it? But this github project is dead. I want to open issues and PRs, but no one is looking at this.

I'd like to know sooner rather than later if Google is abandoning it.

Thanks!

**Comment by vikramspringml** [comment]
Same question here ? Any updates Googlers?

**Comment by borgilb** [comment]
I've been lead to believe its not being deprecated inside Google at least.

I will say though I really love this project and would like to contribute, if not code, issues and feature requests.

**Comment by RainbowMango** [comment]
> Its officially supported by the GKE UI and from what I have heard possible future GKE features might use it?

@borgilb Any links to the GKE UI? I'm interested in this project too.

**Comment by red8888** [comment]
@RainbowMango https://cloud.google.com/solutions/using-gke-applications-page-cloud-console

**Comment by RainbowMango** [comment]
Thanks @red8888

**Comment by nuclearwu** [comment]
> ny updates Googlers?

Hi @RainbowMango ，Is it possible to integrate some concepts of this project about applications into karmada to achieve application distribution and management across multiple clusters

**Comment by nuclearwu** [comment]
> Thanks @red8888

Hi @RainbowMango ，Is it possible to integrate some concepts of this project about applications into karmada to achieve application distribution and management across multiple clusters

**Comment by RainbowMango** [comment]
Yeah, I was thinking about it. The concepts of this project are great.

/remove-lifecycle stale

**Comment by borgilb** [comment]
@nuclearwu not really. Things like Karmada are huge platforms sweeping in scope/goals. Having to adopt something like that for this purpose is wildly heavy handed.

The Application CRD does the following:
1. Provide a metadata object you can add arbitrary data do that is deployed with your stack
