### ISSUE TITLE
Nest Application metadata fields

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#28]
I'd separate the metadata fields about an application, like `description, keywords...` from the fields holding some logic like `matchLabels`, `componentKinds`. 

First, it's more clear for the user and tools authors to spot what is informative only and what is modifying the behavior of the controller 
Second, the descriptor spec could be more easily reused by other project and integrated to different CRD.

related comment (from the kinflate initial PR): https://github.com/kubernetes/kubernetes/pull/52570#discussion_r140929592
 
``` go
  type Application struct {
     
     // Metadata about the app. 
     descriptor Descriptor            
     ...
 }

  // Descriptor is a convenience struct gathering metadata to support
  // Manifest search, browse and updates.
  type Descriptor struct {
     Name string
     Version string
     Description string
     Icon string
     Keywords []string
     Homepage string
     ...
  }
```

**Comment by ant31** [comment]
@kow3ns if you agree with this I can try to submit the PR

**Comment by ant31** [comment]
> I like it, but I'd like to get adnan's opinion and konrad
cc @konryd

**Comment by prydonius** [comment]
+1 I think this be a nice differentiator

**Comment by jzelinskie** [comment]
+1 to this

Feels like there's precedence with fields like TypeMeta and ObjectMeta

**Comment by kow3ns** [comment]
@ant31 you don't need my permission :) It looks like their is general support
