### ISSUE TITLE
How will objects be selected 

### ISSUE THREAD

**Issue by barry8schneider** [kubernetes-sigs/application#29]
I am not clear what values from within the Application CRD will be used to select the objects that will define my Application within the cluster.

My assumption is that values defined in the Application CRD will be used to query cluster objects which will then define my Application. 

Is the selector the single value spec.selector or is the selection also limited by spec.componentKinds?

Is the selection does by the Application controller and/or by the third party tool? The tool provider would get the selector from the CRD and then query for the objects?

**Comment by barry-schneider** [comment]
I am not clear how the list of components will be provided to the user/vendor. Will the controller return a list of components and/or will the user/vendor take the spec info and query Kubernetes directly?

**Comment by barry-schneider** [comment]
What about namespace?

**Comment by barry-schneider** [comment]
Will the Application controller have adequate permissions to query all of the components in the cluster?

**Comment by kalantar** [comment]
Could someone explain the motivation for including `componentKinds` are included in the model? The only use case that I can see is to query the list of resources. Having a list of kinds seems like an optimization.
