### ISSUE TITLE
Proposed Controller Road Map

### ISSUE THREAD

**Issue by barry8schneider** [kubernetes-sigs/application#33]
What logic should the application controller provide?

**Comment by konryd** [comment]
Two things that come to my mind:
1. Repeatedly issue selector/groupkind queries and update ownerReferences on the components.
2. Ping the healthCheck endpoint (if there's consensus to add it) and update a field in ApplicationStatus ("ApplicationStatus.condition"?).

**Comment by kow3ns** [comment]
I think the main things we want to tackle initially are outlined in #11 #7 #6
