### ISSUE TITLE
Proposed Application Status Type

### ISSUE THREAD

**Issue by barry8schneider** [kubernetes-sigs/application#37]
What information do we want to store in the [Status fields](https://github.com/kubernetes-sigs/application/blob/master/pkg/apis/app/v1alpha1/application_types.go)?

**Comment by dlorenc** [comment]
Good question! Some references to other Status fields in Kubernetes:
[PodStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podstatus-v1-core)
[ContainerStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#containerstatus-v1-core)

Given that basic health checks are in-scope for this CRD, something like the `ready` field on `ContainerStatus` would make sense, though we may need something more detailed than a `bool` here.

`startTime` is another field that makes sense here.

**Comment by kow3ns** [comment]
I think this might be a dup of #11
