### ISSUE TITLE
Is Operator Framework a complement or competitor technology?

### ISSUE THREAD

**Issue by barry8schneider** [kubernetes-sigs/application#40]
Red Hat and the Kubernetes open source community today share the [Operator Framework](https://github.com/operator-framework) – an open source toolkit designed to manage Kubernetes native applications, called Operators, in a more effective, automated, and scalable way.

- Operator SDK: Enables developers to build Operators based on their expertise without requiring knowledge of Kubernetes API complexities.
- Operator Lifecycle Management: Oversees installation, updates, and management of the lifecycle of all of the Operators (and their associated services) running across a Kubernetes cluster.
- Operator Metering (joining in the coming months): Enables usage reporting for Operators that provide specialized services.

**Comment by kow3ns** [comment]
I'd say complementary. The Spark operator will use the Application resource.

**Comment by jzelinskie** [comment]
We do need to work together to get rid of the redundancy between the ClusterServiceVersion-v1 resource used to install Operators and the Application Definition. [See this example of the Vault Operator](https://github.com/operator-framework/operator-lifecycle-manager/blob/115c38e9a8f86a15c6bd5e4e0eec0e0be92712ff/catalog_resources/ocs/vaultoperator.0.1.9.clusterserviceversion.yaml).

The Lifecycle Manager is a controller that has built out behavior similar to the discussed functionality for a controller for the Application Definition, so ideally we can cross pollinate.

**Comment by resouer** [comment]
@jzelinskie The use case in Alibaba is we are seeking for a mechanism to audit and manage all CRDs and controllers in a unified way. i.e. A meta CRD for applications. The idea of Application does match the expectation, and I am thinking if it's possible for Operator framework to adopt similar idea as well? Or, maybe it's already happening?

**Comment by jzelinskie** [comment]
The Application CRD schema is largely inspired by the metadata used in OLM's Resources when it was a part of Tectonic. However, that's where the similarities end. At this point in time, the Application CRD is for managing arbitrary groups of resources. It does not want to become any more opinionated than that.

The OLM component of the Operator Framework is for very specifically for managing Operators (a Deployment of a controller and a CRD). We think that complex applications should become a part of the Kubernetes control plane. If you wanted to use this solution at Alibaba, know that you'd also have to buy into some of our opinions on how Operators should work, like enforcing owner references, for example.
