### ISSUE TITLE
Primary link attribute?

### ISSUE THREAD

**Issue by keithguerin** [kubernetes-sigs/application#46]
Many apps provide a primary link (e.g. PhpMyAdmin, WordPress admin, IP address) that is the user's main destination. It looks like this link is typically put into "infoItems" array. Would it be useful to define an attribute for 'primaryLink', so it is easier to identify and highlight in a UI?

**Comment by jzelinskie** [comment]
For long term flexibility, I'd prefer this be convention rather than anything directly in the schema. Apps can have multiple "primary" endpoints.

**Comment by keithguerin** [comment]
That makes sense Jimmy. Any suggestions on how to promote this convention? How would users/UI developers be able to identify these links?

**Comment by deustis** [comment]
A convention that might be somewhat intuitive: take the first "link" in the info items list, which might be a URL string, or a reference to a Secret or Ingress.
