### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by mattfarina** [kubernetes-sigs/application#5]
This project needs some clear docs on:

* Why this project exists (current problem and value proposition)
* Installing into a cluster
* How to use the CRD
* Documentation on what properties can be used
* How someone should use owner references alongside the CRD
* The difference between an application and an application instance?
* Contributing documentation on how and when to use kubebuilder with project
* Contributing docs on updating the installation of this project in a cluster

I imagine there are others. This is just a first pass.

**Comment by mattfarina** [comment]
Noted kubebuilder in contributing docs via #8

**Comment by deustis** [comment]
In particular, the instructions for installing the CRD need some improvement. They currently reference a "hack" manifest: `application/hack/install.yaml`. That manifest also contains a Service and StatefulSet which do not appear to be relevant to the spec.
