### ISSUE TITLE
Ownership between custom resources and Applications

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-sigs/application#57]
Issue #7 is about putting `OwnerReference` onto components that comprise an `Application`. I would like to use this issue to open some discussion on the ownership between custom resources and `Applications`. Here's a scenario: suppose there's a CRD for a type of applications, which need a set of Kubernetes resources to run, e.g.,  a StatefulSet, some Service, and also some other resources. The corresponding Kubernetes operator watches instances of the CRD kind and creates the necessary resources for each newly created custom resource instance. When creating the resources, the operator adds an `OwnerReference` to each of the resources referencing the instance. The reason for this is when the user deletes the custom resource object, the resources get garbage collected. 

Additionally, to allow components of each application instance to be logically grouped, an `Application` instance is also created by the operator. So the `Application` instance is created as a result of the operator seeing the custom resource instance and it probably makes sense to have the custom resource object "owns" the `Application` instance. However, it might also makes sense (although debatable I guess) the other way around if the custom resource instance is owned by the `Application` instance as part of the logic group of components supporting the application. The former is straightforward to realize but the latter faces the same problem #7 discussed.

I would like to hear others' thoughts on this.

**Comment by mattfarina** [comment]
@liyinan926 This is a great topic to bring up. Thanks for doing it.

Consider the case of cross-compatibility of tools. This is what ultimately drove the creation of the application crd. What if someone finds the application created/managed by the operator in a UI like dashboard. Then they choose to delete it there. How will the cascading delete work from there?

The idea is to consider how people will use in when varying tools and user activities are involved.

**Comment by liyinan926** [comment]
@erictune

**Comment by crimsonfaith91** [comment]
@liyinan926 IMO, the CRD object should own the `Application` instance. We will always have one CRD object, but users may want to have multiple `Application` instances.

**Comment by jzelinskie** [comment]
cc @ecordell

Users that choose to create Applications that encapsulate groups of CRs that are owned by Operators should have no issue. If a Resource is owned by a CR, it is the domain of an Operator, even if that resource is an Application or any type of CR. If a user deletes it, the Operator should properly restore the objects to their desired state. I'm not so sure there's an issue here beyond user experience trying to filter Resources they control vs Operator owned resources. To be fair, effects Kubernetes core APIs like a user deleting the pods of a ReplicaSet/Deployment. To improve this UX, I think we could use better APIs for querying OwnerReferences.

**Comment by liyinan926** [comment]
@crimsonfaith91 I probably didn't make it clear. I didn't mean CustomResourceDefinitions themselves, but rather custom resources conforming to some CustomResourceDefinitions observed by a custom controller. There's a one-to-one mapping between a custom resource of a certain CRD type and the corresponding Application instance.

**Comment by crimsonfaith91** [comment]
@liyinan926 Noted. What you intended to mean is custom resource _instance_, not CRD. In this case, I think the application instance should be owned by the custom resource instance because the application instance is created _after_ the custom resource instance.
