### ISSUE TITLE
Improve end-user installation instructions

### ISSUE THREAD

**Issue by deustis** [kubernetes-sigs/application#60]
The current [instructions](https://github.com/kubernetes-sigs/application#installing-the-crd) could use some improvement.

A few suggestions:
- Make a minimal manifest with only the CRD (i.e. remove namespace, statefulset, etc.) 
- Put the manifest in a friendlier location (i.e. not "hack" directory)
- Put the relative path to the manifest in the command-line instructions.
- Nice to have: a section with some explanation about how to manage multiple CRD verisons.

**Comment by ensonic** [comment]
+1, the controlelr does nothing, hence for simple experiments, I'll like to just deploy the crd. Maybe use a subdir and split the yaml into parts.

**Comment by ensonic** [comment]
For the time beeing here is a copy of the app.crd as standalone file:
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/crd/app-crd.yaml

**Comment by jlegrone** [comment]
Addressing #69 should help with this since newer versions of kubebuilder use kustomize:

https://book.kubebuilder.io/beyond_basics/deploying_controller.html

**Comment by garethr** [comment]
The current installation instructions also assume this is checked out in GOPATH. If it's not then `make manifests` fails as it can't find the vendor directory. If someone isn't familiar with the Go toolchain then that can be tricky to work out.
