### ISSUE TITLE
Installing as per instructions fails

### ISSUE THREAD

**Issue by subwiz** [kubernetes-sigs/application#64]
I [followed the instructions](https://book.kubebuilder.io/getting_started/installation_and_setup.html), and get this error:

```
$ kubebuilder
2018/09/06 14:33:51 kubebuilder must be run from the project root under $GOPATH/src/<package>.
Current GOPATH=/Users/subhash/gopath.
Current directory=/Users/subhash
```

I'm using Mac High Sierra.

**Comment by bsalmi** [comment]
I have the same issue, I'm using CentOS 7

**Comment by cizezsy** [comment]
The same issue, I'm using Fedora 28.

**Comment by jlegrone** [comment]
I believe this is related to #69, as that's the latest documentation for kubebuilder. You should be able to build locally by following these instructions:

https://github.com/kubernetes-sigs/application/tree/42782aebdc651ba13071eebd6b58d50484237b37#controller
