### ISSUE TITLE
Please add a roadmap

### ISSUE THREAD

**Issue by bassam** [kubernetes-sigs/application#65]
Would be great to see a roadmap for this project. What are you planning to do next and in what timeframe?

**Comment by cmoulliard** [comment]
I agree with you that having a roadmap like also how the project will be released and what will be its release cadence is needed.

Will it be possible to release the API describing the `Application Custom`'s resource separated from the Controller as projects developing controler/operator using a different toolkit such as [operator-sdk](https://github.com/operator-framework/operator-sdk) could then leverage the work done by this project ?
