### ISSUE TITLE
Application should comprise components across namespaces

### ISSUE THREAD

**Issue by cvignola** [kubernetes-sigs/application#67]
**Proposed:**  add namespace qualification to 'componentKinds' 

**Discussion:**

It is abundantly clear that cloud native applications may be comprised of resources from multiple namespaces. 

Scenarios: 

- One scenario is that an Application corresponds exactly to a set of resources that are deployed together, and deployed to the same namespace.  This scenario is most easily described as a single team, deploying multiple resources with a single helm chart, all to the same namespace.  

- Another scenario is that an Application corresponds to a set of resources, some of which are deployed together (e.g. single team, as above), as well as others that are deployed separately (perhaps shared services) by other teams.  We should not assume all teams deploy to the same namespace.

For example,  my stock-trader application is comprised of these components: 

1. stocktrader UI (ns=stocktrader)
1. trader (ns=stocktrader)
1. quote (ns=stocktrader)
1. portfolio (ns=stocktrader)
1. loyalty (ns=loyalty, a shared service)
1. messaging (ns=services, a shared service)

The preceding list makes the point that an application's components - the very ones the user wants to regard as being part of their application  - may be deployed as part of the principle application (i.e. stocktrader, in this example), as well as include services deployed by other teams (e.g. loyalty and messaging).  

To describe an application whose components are in various namespaces requires a way to specify that fact.  I propose we add namespace to componentKinds, e.g., like this: 

```
componentKinds
     - group: deployments-stocktrader
        kind: Deployment 
        namespace: stocktrader
    - group: deployments-loyalty
       kind: Deployment 
       namespace:  loyalty
    - group: deployments-services
       kind: Deployment
       namespace: services 
```

**Comment by prydonius** [comment]
FYI one issue with this is that ownerReferences [cannot cross namespaces](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents). We'd need to make Application a cluster-scoped resource in order for resources across namespaces to owned by it (or introduce a separate ClusterApplication CRD).
