### ISSUE TITLE
To federate Application CRD

### ISSUE THREAD

**Issue by shaoxt** [kubernetes-sigs/application#71]
If a company have multiple cluster,   how does Application replicate to all clusters?

**Comment by cmoulliard** [comment]
You will need such a lib [1] to be able to watch a resource on multiple clusters and of course to deploy the resources on all the resources

[1] https://github.com/admiraltyio/multicluster-controller

**Comment by ensonic** [comment]
Maybe @shaoxt meant that parts of an app run on one cluster and other part on another cluster. Right now the app CRD only seems to connect an app name (and related metadata) with a label selector plus a restriction of kinds.

**Comment by ensonic** [comment]
FYI: for multicluster fedaration we've build
https://github.com/googlecloudrobotics/core/blob/master/docs/concepts/federation.md
this leave the challenge for app-crd to reference the parts on other clusters.

/remove-lifecycle stale
