### ISSUE TITLE
spec.componentKinds not sufficiently described

### ISSUE THREAD

**Issue by ensonic** [kubernetes-sigs/application#72]
In README.md spec.componentKinds lack descriptions for the 'group' key. This seems to be either empty, `core` or `apps` in the samples. Please describe.
Also the GroupKind is written as a link, but the link target does not exists.

**Comment by deustis** [comment]
The `group` key refers to the resource's [API Group](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-group). 

The README description should be updated to add that link. Also, I just noticed the README has an example where the group field is empty. This was originally a short-hand for "core", but I believe the short-hand is now discouraged.

**Comment by ensonic** [comment]
Thanks for the explanation. Before I send a PR to update it, do I understand right that the purpose of specifying the componentKinds is additional filtering on top of the label selector?

**Comment by deustis** [comment]
It is more like a necessity so that the client (e.g. a console UI) knows which APIs to list (before matching against the label). It does also have the implication of being an additional filter on top of the label.

**Comment by ensonic** [comment]
FYI, there is a PR in https://github.com/kubernetes-sigs/application/pull/74 since two weeks, that ways for review/merge.
