### ISSUE TITLE
Status Aggregation for Application CRD

### ISSUE THREAD

**Issue by barney-s** [kubernetes-sigs/application#76]
## Background
Application CRD has a list of GroupKinds and a LabelSelector to logically group live objects in the cluster. The Application CRD also provides a way to attach descriptive metadata to the logical grouping. 

## What does this solve
This proposes to enhance Application CRD controller to provide status tracking for the objects that match the selectors. This dramatically simplifies the status tracking requirements for a client that uses Application CRD. 

## Proposal
The proposal is to add a reconciler that creates watches for the GroupKinds that the application CRD refers to. The reconciler then inspects the matching objects and updates the aggregate status in the Application CRD.

Please review the attached proposal: https://github.com/kubernetes-sigs/application/pull/77

**Comment by barney-s** [comment]
@kow3ns please review the proposal.

**Comment by enisoc** [comment]
@barney-s Could you copy the markdown into an .md file and make a PR to add that file to a new `docs/proposals/` dir in the repo? That would make it easier to make comments on specific parts.

**Comment by barney-s** [comment]
> @barney-s Could you copy the markdown into an .md file and make a PR to add that file to a new `docs/proposals/` dir in the repo? That would make it easier to make comments on specific parts.

Done: https://github.com/kubernetes-sigs/application/pull/77

**Comment by kow3ns** [comment]
I borrowed from the prior and came up with a new issue https://github.com/kubernetes-sigs/application/issues/78

**Comment by barney-s** [comment]
#81 merged for this
