### ISSUE TITLE
Proposal: Flag to adopt resources 

### ISSUE THREAD

**Issue by barney-s** [kubernetes-sigs/application#86]
Proposal is for adopting resources that match the AppCRD selectors.
```yaml
# Flag that indicates matched resources must be adopted
.spec.adopt: true
```

In some use cases where application crd is used, the tooling explicitly sets OwnerReference of the objects (that match appcrd selectors) to point to the Application object.

Can we make this automatic controller by a flag that is turned off by default.

**Comment by barney-s** [comment]
@kow3ns @huyhg FYI

**Comment by ant31** [comment]
related to https://github.com/kubernetes-sigs/application/issues/7
