### ISSUE TITLE
Does the Application operator supports Components ?

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/application#91]
I'm a bit confused about how the Application operator populates a list of components from an Application

This [code](https://github.com/kubernetes-sigs/application/blob/c70fb844daa792f9a3952c4b09dbaab84c5d019c/pkg/genericreconciler/genericreconciler.go#L123) is responsible to get the components of a resource

```
components := rsrc.Components()
			for _, component := range components {
```
but if I look to the code [developed](https://github.com/kubernetes-sigs/application/blob/150213da1203c3b27f04794c118a9f407c29344d/pkg/apis/app/v1beta1/application.go#L130-L140)

```
// Components returns components for this resource
func (a *Application) Components() []component.Component {
	c := []component.Component{}
	c = append(c, component.Component{
		Handle:   a,
		Name:     "app",
		CR:       a,
		OwnerRef: a.OwnerRef(),
	})
	return c
}
```
a `Component` is appended to the list and the `Component` is always created using the current application

Questions : 
- Is the plan of the Application CRD to also contains Components which corresponds to others Applications (see composition proposition as defined within the [original kep](https://goo.gl/hCwSzW)) ?
- If the Application CRD will support such a composition, where within the spec do you plan to define such components list as the purpose of the [`ComponentGroupKinds`](https://goo.gl/JK3hKe) of the spec is to group the k8s resources created or to be created for an application ? 

@ant31 @mattfarina @barney-s

**Comment by barney-s** [comment]
The guts of this controller is borrowed from another controller which has multiple components (composition). The application controller is just a single component, the AppCR itself.

May be in future once we decide to support explicit composition/grouping in AppCRD specification, we could potentially use components.Components to reconcile the appcrd.groups/components separately.

**Comment by cmoulliard** [comment]
Could we then better document what has been done, how it should be used and removed then what is not needed ? @barney-s @ant31 @mattfarina
