### ISSUE TITLE
[Suggestion] Add EnVarFromSource as new InfoItemSourceType

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/application#93]
## Description

The `InfoItemSource` allows to identify the type of the information we want to capture using an `InfoItem`. This information is defined using the [InfoItemSourceType](https://github.com/kubernetes-sigs/application/blob/master/pkg/apis/app/v1beta1/application_types.go#L217-L242).

Unfortunately, the existing list of `const` as defined hereafter does not include the Kubernetes type: `EnvVarFrom` [1]. 

Existing Source's types

```
type InfoItemSource struct {
	// Type of source.
	Type InfoItemSourceType `json:"type,omitempty"`
...
}

// InfoItemSourceType is a string
type InfoItemSourceType string

// Constants for info type
const (
	SecretKeyRefInfoItemSourceType    InfoItemSourceType = "SecretKeyRef"
	ConfigMapKeyRefInfoItemSourceType InfoItemSourceType = "ConfigMapKeyRef"
	ServiceRefInfoItemSourceType      InfoItemSourceType = "ServiceRef"
	IngressRefInfoItemSourceType      InfoItemSourceType = "IngressRef"
)
```

## Suggestion

We propose to extend the list of the `InfoItemSourceType` const in order to include the EnvVarFromSource

```
const (
	EnvVarFromSourceRefInfoItemSourceType    InfoItemSourceType = "EnvVarFromSourceRef" // Refer to either a Secret or ConfigMap
)
```
[1] : https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#envvarsource-v1-core

WDYT @ant31 @barney-s @mattfarina ?

**Comment by ant31** [comment]
I would even go a step further:

I'm not sure why it should be limited to any field? 
Couldn't we use ObjectRef to all fields, like it is done in https://github.com/kubernetes-sigs/kustomize ?

Say I want to bubble up an annotation or some field in a CRD to display it in a UI/InfoItems

**Comment by cmoulliard** [comment]
If we can generalize, why not. I will have a look and provide then a PR.

**Comment by cmoulliard** [comment]
Where do you see that kustomize use `ObjectRef` @ant31 within their code ?

**Comment by ant31** [comment]
> does that means that the k8s resource must be created and deployed on k8s cluster
Where else could they be deployed?

**Comment by mattfarina** [comment]
@kow3ns thoughts? Why do we limit it?

**Comment by cmoulliard** [comment]
> Couldn't we use ObjectRef to all fields

As some types are not published as K8s Kind/object, then we can't use at all `ObjectRef` but instead an object which is of type `interface {}`

Here is an example 

```
package main

import (
	"fmt"

	"github.com/davecgh/go-spew/spew"
	"github.com/ghodss/yaml"
	corev1 "k8s.io/api/core/v1"
	"testing"
)

// InfoItemType is a string that describes the value of InfoItem
type InfoItemType string

// InfoItemSource represents a source for the value of an InfoItem.
type InfoItemSource struct {}

// InfoItem is a human readable key,value pair containing important information about how to access the Application.
type InfoItem struct {
	// Name is a human readable title for this piece of information.
	Name string `json:"name,omitempty"`

	// Type of the value for this InfoItem.
	Type InfoItemType `json:"type,omitempty"`

	// Value is human readable content.
	Value string `json:"value,omitempty"`

	// ValueFrom defines a reference to derive the value from another source.
	ValueFrom *InfoItemSource `json:"valueFrom,omitempty"`

	Object interface{}
}

var data = `
Name: Spring Boot v1
Type: EnvVar
Object: 
  - key: JAVA_HOME
    value: /usr/local/bin/java
`

func TestUnMarshalling(t *testing.T) {
	// Initialize the variable p as type Person.
	infoItem := InfoItem{}
	err := yaml.Unmarshal([]byte(data), &infoItem)
	if err != nil {
		fmt.Print(err.Error())
	}

	spew.Dump(CreateEnvVar(infoItem.Type, infoItem.Object))
}

func CreateEnvVar(Type InfoItemType, obj interface{}) *[]corev1.EnvVar {
	envVars := []corev1.EnvVar{}

	r := obj.([]interface{})
	for _, i := range r {
		m := i.(map[string]interface{})
		n := m["key"].(string)
		v := m["value"].(string)

		if Type == "EnvVar" {
			env := corev1.EnvVar{
				Name:  n,
				Value: v,
			}
			envVars = append(envVars, env)
			return &envVars
		}
	}
	return nil
}
```

WDYT @ant31 @mattfarina @kow3ns ?

**Comment by ant31** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/var.go#L29-L47

Shortcut my be useful but it works by using both information objectRef and fieldRef
example: 
```
 - objref:
        kind: Deployment
        name: myapp
        apiVersion: apps/v1
   fieldref:  metadata.annotations.git-ref
```

**Comment by cmoulliard** [comment]
@ant31 This approach will be horribly complex if I want by example to define a List of `EnvVars`. How can I define the `fieldRef` in this case ? How the validation using [`openApi v3 Schema`](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation) could then take place ?
